import { ArrowLeft, ArrowRight, Check, FileText, Gem, ShieldCheck } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { Link } from "wouter";
import PublicHeader from "@/components/PublicHeader";
import PublicFooter from "@/components/PublicFooter";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";

const initialForm = { fullName: "", mobile: "", email: "", address: "", occupation: "", monthlyIncome: "", loanType: "personal", requiredAmount: "", purpose: "", repaymentFrequency: "monthly", preferredDuration: "12", collateralType: "none", collateralDetails: "", estimatedValue: "", referenceNumber: "" };

export default function Apply() {
  const { t } = useLanguage();
  const [step, setStep] = useState(1);
  const [form, setForm] = useState(() => ({ ...initialForm, loanType: new URLSearchParams(window.location.search).get("type") || "personal" }));
  const [sent, setSent] = useState(false);
  const [error, setError] = useState("");
  const mutation = trpc.loanApplications.create.useMutation({ onSuccess: () => setSent(true), onError: (err) => setError(err.message || "Please review the form and try again.") });
  const progress = useMemo(() => `${(step / 3) * 100}%`, [step]);
  const update = (key: keyof typeof initialForm, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const next = (event: FormEvent) => { event.preventDefault(); setError(""); if (step < 3) setStep((current) => current + 1); else mutation.mutate({ ...form, monthlyIncome: Number(form.monthlyIncome), requiredAmount: Number(form.requiredAmount), preferredDuration: Number(form.preferredDuration), estimatedValue: form.estimatedValue ? Number(form.estimatedValue) : undefined }); };

  if (sent) return <div className="public-site"><PublicHeader /><main className="success-page"><div className="success-page__mark"><Check size={28} /></div><p className="eyebrow"><span className="eyebrow-line" />{t("apply.eyebrow")}</p><h1>Thank you. Your application is on its way.</h1><p>{t("apply.success")}</p><Link href="/" className="button button--orange">Return home <ArrowRight size={17} /></Link></main><PublicFooter /></div>;

  return <div className="public-site"><PublicHeader /><main className="apply-page"><div className="site-container apply-page__inner"><div className="apply-intro"><Link href="/" className="back-link"><ArrowLeft size={16} /> {t("common.back")}</Link><p className="eyebrow"><span className="eyebrow-line" />{t("apply.eyebrow")}</p><h1>{t("apply.heading")}</h1><p>{t("apply.body")}</p><div className="apply-trust"><ShieldCheck size={18} /><span>Your information is reviewed only for this application.</span></div></div><div className="application-card"><div className="application-card__top"><div className="stepper"><span className={step >= 1 ? "is-active" : ""}>01 <small>{t("apply.step1")}</small></span><i /><span className={step >= 2 ? "is-active" : ""}>02 <small>{t("apply.step2")}</small></span><i /><span className={step >= 3 ? "is-active" : ""}>03 <small>{t("apply.step3")}</small></span></div><div className="step-progress"><span style={{ width: progress }} /></div></div><form onSubmit={next}>
    {step === 1 && <div className="form-step"><div className="form-step__heading"><span>01</span><div><h2>{t("apply.step1")}</h2><p>Share the essentials so we can understand your request.</p></div></div><div className="form-grid form-grid--two"><Field label={t("apply.fullName")} value={form.fullName} onChange={(v) => update("fullName", v)} required /><Field label={t("apply.mobile")} value={form.mobile} onChange={(v) => update("mobile", v)} type="tel" required /><Field label={t("apply.email")} value={form.email} onChange={(v) => update("email", v)} type="email" required /><Field label={t("apply.occupation")} value={form.occupation} onChange={(v) => update("occupation", v)} required /><Field label={t("apply.income")} value={form.monthlyIncome} onChange={(v) => update("monthlyIncome", v)} type="number" required /><Field label={t("apply.address")} value={form.address} onChange={(v) => update("address", v)} textarea required /></div></div>}
    {step === 2 && <div className="form-step"><div className="form-step__heading"><span>02</span><div><h2>{t("apply.step2")}</h2><p>Tell us about the amount and repayment rhythm you prefer.</p></div></div><div className="form-grid form-grid--two"><SelectField label={t("apply.loanType")} value={form.loanType} onChange={(v) => update("loanType", v)} options={["personal", "home", "bike", "car", "emergency", "business"].map((key) => ({ value: key, label: t(`loan.${key}`) }))} /><Field label={t("apply.requiredAmount")} value={form.requiredAmount} onChange={(v) => update("requiredAmount", v)} type="number" required /><Field label={t("apply.purpose")} value={form.purpose} onChange={(v) => update("purpose", v)} textarea required /><SelectField label={t("apply.frequency")} value={form.repaymentFrequency} onChange={(v) => update("repaymentFrequency", v)} options={["daily", "weekly", "monthly"].map((key) => ({ value: key, label: t(`frequency.${key}`) }))} /><Field label={t("apply.duration")} value={form.preferredDuration} onChange={(v) => update("preferredDuration", v)} type="number" required /></div></div>}
    {step === 3 && <div className="form-step"><div className="form-step__heading"><span>03</span><div><h2>{t("apply.step3")}</h2><p>{t("apply.collateralNote")}</p></div></div><div className="form-grid form-grid--two"><SelectField label={t("apply.collateralType")} value={form.collateralType} onChange={(v) => update("collateralType", v)} options={["none", "gold", "silver", "bike", "car", "property", "phone", "laptop", "other"].map((key) => ({ value: key, label: t(`collateral.${key}`) }))} /></div>{form.collateralType !== "none" && <div className="collateral-detail-panel"><div className="collateral-detail-panel__icon">{["gold", "silver"].includes(form.collateralType) ? <Gem size={20} /> : <FileText size={20} />}</div><div><h3>{t(`collateral.${form.collateralType}`)}</h3><p>Only the details relevant to this collateral type are shown.</p></div><div className="form-grid form-grid--two"><Field label={t("apply.collateralDetails")} value={form.collateralDetails} onChange={(v) => update("collateralDetails", v)} textarea required /><Field label="Estimated value" value={form.estimatedValue} onChange={(v) => update("estimatedValue", v)} type="number" required />{["bike", "car", "property"].includes(form.collateralType) && <Field label="Document / reference number" value={form.referenceNumber} onChange={(v) => update("referenceNumber", v)} required />}</div></div>}</div>}
    {error && <p className="form-error">{error}</p>}<div className="application-card__actions">{step > 1 ? <button type="button" className="button button--ghost" onClick={() => setStep((current) => current - 1)}><ArrowLeft size={16} /> {t("apply.previous")}</button> : <span />}{step < 3 ? <button type="submit" className="button button--orange">{t("apply.next")} <ArrowRight size={17} /></button> : <button type="submit" className="button button--orange" disabled={mutation.isPending}>{mutation.isPending ? t("common.loading") : t("apply.submit")} <ArrowRight size={17} /></button>}</div>
  </form></div></div></main><PublicFooter /></div>;
}

function Field({ label, value, onChange, type = "text", textarea = false, required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; textarea?: boolean; required?: boolean }) {
  return <label className="field"><span>{label}</span>{textarea ? <textarea value={value} onChange={(event) => onChange(event.target.value)} required={required} rows={3} /> : <input type={type} value={value} onChange={(event) => onChange(event.target.value)} required={required} />}</label>;
}

function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: { value: string; label: string }[] }) {
  return <label className="field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</select></label>;
}
