import { BarChart3, CalendarDays, CircleDollarSign, PieChart as PieIcon } from "lucide-react";
import { useLanguage } from "@/contexts/LanguageContext";
import { StatCard, StatusBadge, WorkspacePageHeader } from "@/components/WorkspaceUI";

export function PreviewAdmin() {
  const { t } = useLanguage();
  return <div><WorkspacePageHeader eyebrow="CollatXSmart / Operations" title={t("admin.heading")} body={t("admin.body")} action={<button className="button button--orange">Review requests</button>} /><div className="stats-grid"><StatCard label={t("admin.totalApplications")} value="24" detail="+8 this month" tone="orange" trend="up" /><StatCard label={t("admin.activeLoans")} value="12" detail="Across all products" tone="blue" /><StatCard label={t("admin.outstanding")} value="₹8,42,000" detail="Principal outstanding" tone="neutral" /><StatCard label={t("admin.collection")} value="₹1,26,500" detail="+12.6% this month" tone="green" trend="up" /></div><div className="chart-grid"><section className="workspace-panel chart-panel"><div className="panel-heading"><div><span className="panel-kicker">Portfolio</span><h2>{t("admin.loanMix")}</h2></div><PieIcon size={20} /></div><div className="chart-layout"><div className="preview-donut"><span>24<small>applications</small></span></div><div className="chart-legend"><div><span style={{ background: "#ff5a1f" }} /><span>Personal loan</span><strong>11</strong></div><div><span style={{ background: "#173c35" }} /><span>Business loan</span><strong>6</strong></div><div><span style={{ background: "#b8aa91" }} /><span>Vehicle loan</span><strong>7</strong></div></div></div></section><section className="workspace-panel chart-panel"><div className="panel-heading"><div><span className="panel-kicker">Cash flow</span><h2>{t("admin.collectionTrend")}</h2></div><BarChart3 size={20} /></div><div className="preview-bars"><i style={{ height: "38%" }} /><i style={{ height: "56%" }} /><i style={{ height: "46%" }} /><i style={{ height: "72%" }} /><i style={{ height: "63%" }} /><i style={{ height: "88%" }} /></div></section></div><section className="workspace-panel review-panel"><div className="panel-heading"><div><span className="panel-kicker">Needs attention</span><h2>{t("admin.reviewQueue")}</h2></div><StatusBadge status="under review" /></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Application</th><th>Customer</th><th>Type</th><th>Amount</th><th>Status</th></tr></thead><tbody><tr><td><strong>CXS-2026-00042</strong></td><td>Priya S.</td><td>Home loan</td><td>₹2,40,000</td><td><StatusBadge status="under review" /></td></tr><tr><td><strong>CXS-2026-00041</strong></td><td>Arun K.</td><td>Business loan</td><td>₹4,80,000</td><td><StatusBadge status="documents required" /></td></tr></tbody></table></div></section></div>;
}

export function PreviewCustomer() {
  const { t } = useLanguage();
  return <div><WorkspacePageHeader eyebrow={t("dashboard.customer")} title={t("customer.heading")} body={t("customer.body")} action={<button className="button button--orange">{t("customer.viewLoan")}</button>} /><div className="stats-grid"><StatCard label={t("customer.outstanding")} value="₹1,84,000" detail="Current balance" tone="orange" /><StatCard label={t("customer.nextDue")} value="₹15,300" detail="15 Aug 2026" tone="blue" /><StatCard label={t("customer.totalPaid")} value="₹76,500" detail="Across this loan" tone="green" /><StatCard label={t("customer.loanStatus")} value="Active" detail="Personal loan" tone="neutral" /></div><div className="workspace-grid workspace-grid--two"><section className="workspace-panel"><div className="panel-heading"><div><span className="panel-kicker">{t("customer.schedule")}</span><h2>Next installments</h2></div><CalendarDays size={20} /></div><div className="schedule-list"><div className="schedule-row"><span className="schedule-row__number">01</span><div><strong>Installment 08</strong><small>15 Aug 2026</small></div><strong>₹15,300</strong><StatusBadge status="pending" /></div><div className="schedule-row"><span className="schedule-row__number">02</span><div><strong>Installment 09</strong><small>15 Sep 2026</small></div><strong>₹15,300</strong><StatusBadge status="pending" /></div><div className="schedule-row"><span className="schedule-row__number">03</span><div><strong>Installment 10</strong><small>15 Oct 2026</small></div><strong>₹15,300</strong><StatusBadge status="pending" /></div></div></section><section className="workspace-panel workspace-panel--accent"><div className="panel-heading"><div><span className="panel-kicker">Keep things current</span><h2>Stay ready for the next step.</h2></div><CircleDollarSign size={22} /></div><p className="panel-body-copy">Upload any requested document, review your payment history, or update your contact details.</p><div className="panel-actions"><button className="button button--dark">Upload document</button><a href="#profile" className="text-link">Update profile</a></div></section></div></div>;
}
