import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Language = "en" | "ta";
type TranslationMap = Record<string, string>;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const english: TranslationMap = {
  "brand.name": "CollatXSmart",
  "brand.tagline": "Clearer lending. Stronger futures.",
  "nav.home": "Home",
  "nav.services": "Loan services",
  "nav.how": "How it works",
  "nav.about": "About",
  "nav.contact": "Contact",
  "nav.lab": "CLF Lab",
  "nav.login": "Customer login",
  "nav.apply": "Apply for a loan",
  "hero.eyebrow": "Smart lending for real life",
  "hero.title": "Financial support,",
  "hero.titleAccent": "when you need it.",
  "hero.body": "Flexible loan solutions designed around your needs, income, and repayment comfort — with a human team behind every decision.",
  "hero.apply": "Start an application",
  "hero.explore": "Explore services",
  "hero.note": "Serving Coimbatore and nearby areas in Tamil Nadu",
  "hero.cardTitle": "Your next step",
  "hero.cardBody": "A clear application journey, transparent updates, and one place to track your loan.",
  "hero.cardCta": "See the journey",
  "services.eyebrow": "Purpose-built products",
  "services.heading": "One platform. More ways to move forward.",
  "services.body": "Choose the kind of support that fits your moment. Every loan is assessed around your requirements and repayment capability.",
  "service.personal.title": "Personal loan",
  "service.personal.body": "Flexible support for planned expenses, family needs, and everyday goals.",
  "service.home.title": "Home loan",
  "service.home.body": "A practical financing path for home-related requirements and improvements.",
  "service.bike.title": "Bike loan",
  "service.bike.body": "Financing support for two-wheeler needs without unnecessary complexity.",
  "service.car.title": "Car loan",
  "service.car.body": "Flexible vehicle financing structured around your repayment comfort.",
  "service.emergency.title": "Emergency loan",
  "service.emergency.body": "Quick support for urgent situations, subject to verification and assessment.",
  "service.business.title": "Business loan",
  "service.business.body": "Financial support for working capital, tools, and measured business growth.",
  "common.learnMore": "Learn more",
  "common.viewAll": "View all",
  "common.back": "Back",
  "common.save": "Save changes",
  "common.cancel": "Cancel",
  "common.loading": "Loading",
  "common.submit": "Submit",
  "common.search": "Search",
  "common.status": "Status",
  "common.amount": "Amount",
  "common.date": "Date",
  "common.action": "Action",
  "common.noData": "No records to show yet.",
  "process.eyebrow": "A calmer way to borrow",
  "process.heading": "From application to closure, without the guesswork.",
  "process.1": "Apply",
  "process.2": "Verify",
  "process.3": "Approve",
  "process.4": "Disburse",
  "process.5": "Repay",
  "process.6": "Close",
  "why.eyebrow": "Built for clarity",
  "why.heading": "The essentials, without the noise.",
  "why.flexible": "Flexible loan solutions",
  "why.flexibleBody": "Variable amounts, terms, and repayment frequencies based on your circumstances.",
  "why.tracking": "Transparent repayment tracking",
  "why.trackingBody": "See balances, due dates, and payment history in one clear view.",
  "why.secure": "Secure document management",
  "why.secureBody": "Keep important loan documents organised and available when you need them.",
  "why.support": "Personalised support",
  "why.supportBody": "A local team that explains the next step in plain language.",
  "cta.eyebrow": "Ready when you are",
  "cta.heading": "Let’s find the right loan solution for you.",
  "cta.body": "Start with a few details. Our team will review your request and guide you through the next step.",
  "footer.location": "Coimbatore, Tamil Nadu, India",
  "footer.privacy": "Privacy policy",
  "footer.terms": "Terms",
  "login.eyebrow": "Your financial workspace",
  "login.heading": "Welcome back.",
  "login.body": "Sign in to view your loan status, documents, payment history, and next steps.",
  "login.button": "Continue with secure login",
  "login.back": "Back to website",
  "login.note": "Customer and admin access is protected by role-based permissions.",
  "apply.eyebrow": "Loan application",
  "apply.heading": "Tell us what you need.",
  "apply.body": "A short, guided application. Your personal information stays exactly as you enter it.",
  "apply.step1": "Your details",
  "apply.step2": "Loan requirement",
  "apply.step3": "Collateral",
  "apply.next": "Continue",
  "apply.previous": "Previous",
  "apply.submit": "Send application",
  "apply.success": "Application received. Our team will review it and contact you with the next step.",
  "apply.fullName": "Full name",
  "apply.mobile": "Mobile number",
  "apply.email": "Email address",
  "apply.address": "Address",
  "apply.occupation": "Occupation",
  "apply.income": "Monthly income",
  "apply.loanType": "Loan type",
  "apply.requiredAmount": "Required amount",
  "apply.purpose": "Purpose",
  "apply.frequency": "Repayment frequency",
  "apply.duration": "Preferred duration",
  "apply.collateralType": "Collateral type",
  "apply.collateralDetails": "Collateral details",
  "apply.collateralNote": "Only add collateral details if they apply to your request.",
  "apply.select": "Select an option",
  "loan.personal": "Personal loan",
  "loan.home": "Home loan",
  "loan.bike": "Bike loan",
  "loan.car": "Car loan",
  "loan.emergency": "Emergency loan",
  "loan.business": "Business loan",
  "frequency.daily": "Daily",
  "frequency.weekly": "Weekly",
  "frequency.monthly": "Monthly",
  "collateral.none": "No collateral",
  "collateral.gold": "Gold",
  "collateral.silver": "Silver",
  "collateral.bike": "Bike documents",
  "collateral.car": "Car documents",
  "collateral.property": "Home/property documents",
  "collateral.phone": "Mobile phone",
  "collateral.laptop": "Laptop",
  "collateral.other": "Other approved collateral",
  "dashboard.overview": "Overview",
  "dashboard.loans": "Loans",
  "dashboard.payments": "Payments",
  "dashboard.documents": "Documents",
  "dashboard.profile": "Profile",
  "dashboard.requests": "Loan requests",
  "dashboard.customers": "Customers",
  "dashboard.collateral": "Collateral",
  "dashboard.signOut": "Sign out",
  "dashboard.menu": "Menu",
  "dashboard.admin": "Operations workspace",
  "dashboard.customer": "Customer workspace",
  "admin.heading": "Good morning, admin.",
  "admin.body": "A clear view of applications, collections, and the work that needs attention.",
  "admin.totalApplications": "Total applications",
  "admin.activeLoans": "Active loans",
  "admin.outstanding": "Outstanding balance",
  "admin.collection": "This month’s collection",
  "admin.loanMix": "Loan mix",
  "admin.collectionTrend": "Collection trend",
  "admin.reviewQueue": "Review queue",
  "admin.reviewQueueBody": "Applications that need a decision or document follow-up.",
  "admin.viewRequests": "Review requests",
  "admin.approve": "Approve",
  "admin.reject": "Reject",
  "admin.customersBody": "Customer accounts and profile information.",
  "admin.loansBody": "Active accounts, repayment health, and next due dates.",
  "admin.paymentsBody": "Recent receipts from cash, UPI, and bank transfers.",
  "admin.collateralBody": "Collateral records waiting for verification or review.",
  "admin.documentsBody": "Uploaded files and document verification status.",
  "customer.heading": "Welcome back.",
  "customer.body": "Here is your current loan position and the next thing to keep in view.",
  "customer.outstanding": "Outstanding balance",
  "customer.nextDue": "Next payment due",
  "customer.totalPaid": "Total paid",
  "customer.loanStatus": "Loan status",
  "customer.schedule": "Upcoming schedule",
  "customer.history": "Payment history",
  "customer.viewLoan": "View loan details",
  "customer.upload": "Upload document",
  "customer.updateProfile": "Update profile",
  "customer.profileBody": "Keep your contact and income details current so our team can reach you.",
  "customer.documentsBody": "Store and review the files connected to your loan.",
  "customer.emi": "Installment",
  "customer.due": "Due",
  "customer.paid": "Paid",
  "lab.eyebrow": "Client-side / full-stack learning",
  "lab.heading": "See the browser concepts in motion.",
  "lab.body": "A small interactive lab for the CSS box model and JavaScript hoisting concepts used in this project.",
  "lab.boxTitle": "CSS Box Model",
  "lab.boxBody": "Adjust the controls and see how content, padding, border, and margin change the total footprint.",
  "lab.hoistingTitle": "JavaScript Hoisting",
  "lab.hoistingBody": "Run each example to see how declarations behave before execution reaches the line where they appear.",
  "lab.padding": "Padding",
  "lab.border": "Border",
  "lab.margin": "Margin",
  "lab.content": "Content",
  "lab.totalWidth": "Total width",
  "lab.totalHeight": "Total height",
  "lab.run": "Run example",
  "lab.reset": "Reset",
  "lab.backendEyebrow": "Server-side / backend learning",
  "lab.backendHeading": "Build the ideas behind the API.",
  "lab.backendBody": "Trace a request through Node.js, watch bytes move through a stream, and practice MongoDB CRUD with a safe local playground.",
  "lab.httpTitle": "Node.js HTTP server & APIs",
  "lab.httpBody": "Select a route to see how an HTTP server receives a request and sends a structured API response.",
  "lab.httpRun": "Send request",
  "lab.httpRequest": "Request",
  "lab.httpResponse": "Response",
  "lab.bufferTitle": "Buffers, streams & events",
  "lab.bufferBody": "Turn text into bytes, split it into chunks, and emit events as the stream moves through the pipeline.",
  "lab.bufferInput": "Input text",
  "lab.bufferRun": "Run pipeline",
  "lab.bufferChunks": "Chunks",
  "lab.eventLog": "Event log",
  "lab.mongoTitle": "MongoDB CRUD playground",
  "lab.mongoBody": "Practice create, read, update, and delete operations against an in-memory collection using MongoDB-shaped functions.",
  "lab.mongoCreate": "Create document",
  "lab.mongoRead": "Read collection",
  "lab.mongoUpdate": "Update first",
  "lab.mongoDelete": "Delete first",
  "lab.mongoEmpty": "No documents yet",
  "lab.mongoNote": "This browser-only simulator mirrors MongoDB CRUD patterns without storing real data.",
};

const tamil: TranslationMap = {
  "brand.name": "CollatXSmart",
  "brand.tagline": "தெளிவான கடன். வலுவான எதிர்காலம்.",
  "nav.home": "முகப்பு",
  "nav.services": "கடன் சேவைகள்",
  "nav.how": "எப்படி செயல்படுகிறது",
  "nav.about": "எங்களைப் பற்றி",
  "nav.contact": "தொடர்பு",
  "nav.lab": "CLF ஆய்வகம்",
  "nav.login": "வாடிக்கையாளர் உள்நுழைவு",
  "nav.apply": "கடனுக்கு விண்ணப்பிக்க",
  "hero.eyebrow": "உண்மையான வாழ்க்கைக்கான ஸ்மார்ட் கடன்",
  "hero.title": "தேவைப்படும் நேரத்தில்,",
  "hero.titleAccent": "நிதி ஆதரவு.",
  "hero.body": "உங்கள் தேவைகள், வருமானம் மற்றும் திருப்பிச் செலுத்தும் வசதியை மையமாகக் கொண்டு வடிவமைக்கப்பட்ட நெகிழ்வான கடன் தீர்வுகள்.",
  "hero.apply": "விண்ணப்பத்தைத் தொடங்குங்கள்",
  "hero.explore": "சேவைகளைப் பாருங்கள்",
  "hero.note": "கோயம்புத்தூர் மற்றும் தமிழ்நாடு அருகிலுள்ள பகுதிகளில் சேவை",
  "hero.cardTitle": "உங்கள் அடுத்த படி",
  "hero.cardBody": "தெளிவான விண்ணப்பப் பயணம், வெளிப்படையான நிலைமாற்றங்கள், ஒரே இடத்தில் உங்கள் கடன் தகவல்.",
  "hero.cardCta": "பயணத்தைப் பாருங்கள்",
  "services.eyebrow": "உங்களுக்காக வடிவமைக்கப்பட்ட தயாரிப்புகள்",
  "services.heading": "ஒரே தளம். முன்னேற பல வழிகள்.",
  "services.body": "உங்கள் தேவைக்கு ஏற்ற உதவியைத் தேர்ந்தெடுக்கவும். ஒவ்வொரு கடனும் உங்கள் தேவைகள் மற்றும் திருப்பிச் செலுத்தும் திறனை அடிப்படையாகக் கொண்டு மதிப்பிடப்படும்.",
  "service.personal.title": "தனிநபர் கடன்",
  "service.personal.body": "திட்டமிட்ட செலவுகள், குடும்பத் தேவைகள் மற்றும் அன்றாட இலக்குகளுக்கான நெகிழ்வான உதவி.",
  "service.home.title": "வீட்டு கடன்",
  "service.home.body": "வீடு தொடர்பான தேவைகள் மற்றும் மேம்பாடுகளுக்கான நடைமுறை நிதிப் பாதை.",
  "service.bike.title": "பைக் கடன்",
  "service.bike.body": "தேவையற்ற சிக்கல்கள் இல்லாமல் இருசக்கர வாகனத்திற்கான நிதி உதவி.",
  "service.car.title": "கார் கடன்",
  "service.car.body": "உங்கள் திருப்பிச் செலுத்தும் வசதியை மையமாகக் கொண்ட நெகிழ்வான வாகன நிதி.",
  "service.emergency.title": "அவசர கடன்",
  "service.emergency.body": "சரிபார்ப்பு மற்றும் மதிப்பீட்டிற்கு உட்பட்டு அவசர சூழ்நிலைகளுக்கான விரைவு உதவி.",
  "service.business.title": "வணிக கடன்",
  "service.business.body": "செயல்பாட்டு மூலதனம், கருவிகள் மற்றும் அளவான வணிக வளர்ச்சிக்கான நிதி உதவி.",
  "common.learnMore": "மேலும் அறிய",
  "common.viewAll": "அனைத்தையும் பார்க்க",
  "common.back": "பின்",
  "common.save": "மாற்றங்களைச் சேமிக்க",
  "common.cancel": "ரத்து செய்",
  "common.loading": "ஏற்றுகிறது",
  "common.submit": "சமர்ப்பிக்க",
  "common.status": "நிலை",
  "common.amount": "தொகை",
  "common.date": "தேதி",
  "common.action": "செயல்",
  "common.search": "தேடல்",
  "common.noData": "இன்னும் பதிவுகள் இல்லை.",
  "process.eyebrow": "அமைதியான கடன் அனுபவம்",
  "process.heading": "விண்ணப்பத்திலிருந்து நிறைவு வரை, குழப்பமின்றி.",
  "process.1": "விண்ணப்பி",
  "process.2": "சரிபார்",
  "process.3": "ஒப்புதல்",
  "process.4": "வழங்கல்",
  "process.5": "திருப்பிச் செலுத்தல்",
  "process.6": "நிறைவு",
  "why.eyebrow": "தெளிவுக்காக உருவாக்கப்பட்டது",
  "why.heading": "சத்தம் இல்லாமல் தேவையானவை.",
  "why.flexible": "நெகிழ்வான கடன் தீர்வுகள்",
  "why.flexibleBody": "உங்கள் சூழ்நிலைக்கு ஏற்ப மாறுபடும் தொகைகள், கால அளவுகள் மற்றும் திருப்பிச் செலுத்தும் அதிர்வெண்கள்.",
  "why.tracking": "வெளிப்படையான திருப்பிச் செலுத்தல் கண்காணிப்பு",
  "why.trackingBody": "மீதம், செலுத்த வேண்டிய தேதிகள் மற்றும் கட்டண வரலாற்றை ஒரே தெளிவான பார்வையில் காணலாம்.",
  "why.secure": "பாதுகாப்பான ஆவண மேலாண்மை",
  "why.secureBody": "முக்கியமான கடன் ஆவணங்களை ஒழுங்காக வைத்திருந்து தேவையான போது பார்க்கலாம்.",
  "why.support": "தனிப்பட்ட ஆதரவு",
  "why.supportBody": "அடுத்த படியை எளிய மொழியில் விளக்கும் உள்ளூர் குழு.",
  "cta.eyebrow": "நீங்கள் தயாரானபோது",
  "cta.heading": "உங்களுக்கான சரியான கடன் தீர்வைத் தேர்வோம்.",
  "cta.body": "சில விவரங்களுடன் தொடங்குங்கள். எங்கள் குழு உங்கள் கோரிக்கையை மதிப்பாய்வு செய்து அடுத்த படியை விளக்கும்.",
  "footer.location": "கோயம்புத்தூர், தமிழ்நாடு, இந்தியா",
  "footer.privacy": "தனியுரிமைக் கொள்கை",
  "footer.terms": "விதிமுறைகள்",
  "login.eyebrow": "உங்கள் நிதிப் பணியிடம்",
  "login.heading": "மீண்டும் வரவேற்கிறோம்.",
  "login.body": "உங்கள் கடன் நிலை, ஆவணங்கள், கட்டண வரலாறு மற்றும் அடுத்த படிகளைப் பார்க்க உள்நுழையுங்கள்.",
  "login.button": "பாதுகாப்பான உள்நுழைவைத் தொடருங்கள்",
  "login.back": "வலைத்தளத்திற்குத் திரும்பு",
  "login.note": "வாடிக்கையாளர் மற்றும் நிர்வாகி அணுகல் பங்கு அடிப்படையிலான அனுமதிகளால் பாதுகாக்கப்படுகிறது.",
  "apply.eyebrow": "கடன் விண்ணப்பம்",
  "apply.heading": "உங்களுக்கு என்ன தேவை என்று சொல்லுங்கள்.",
  "apply.body": "குறுகிய வழிகாட்டப்பட்ட விண்ணப்பம். உங்கள் தனிப்பட்ட தகவல்கள் நீங்கள் உள்ளிட்டபடியே இருக்கும்.",
  "apply.step1": "உங்கள் விவரங்கள்",
  "apply.step2": "கடன் தேவை",
  "apply.step3": "பிணையம்",
  "apply.next": "தொடர்க",
  "apply.previous": "முந்தையது",
  "apply.submit": "விண்ணப்பத்தை அனுப்புக",
  "apply.success": "விண்ணப்பம் பெறப்பட்டது. எங்கள் குழு அதை மதிப்பாய்வு செய்து அடுத்த படிக்கு உங்களைத் தொடர்புகொள்ளும்.",
  "apply.fullName": "முழுப் பெயர்",
  "apply.mobile": "மொபைல் எண்",
  "apply.email": "மின்னஞ்சல் முகவரி",
  "apply.address": "முகவரி",
  "apply.occupation": "தொழில்",
  "apply.income": "மாத வருமானம்",
  "apply.loanType": "கடன் வகை",
  "apply.requiredAmount": "தேவையான தொகை",
  "apply.purpose": "நோக்கம்",
  "apply.frequency": "திருப்பிச் செலுத்தும் அதிர்வெண்",
  "apply.duration": "விருப்ப கால அளவு",
  "apply.collateralType": "பிணைய வகை",
  "apply.collateralDetails": "பிணைய விவரங்கள்",
  "apply.collateralNote": "உங்கள் கோரிக்கைக்கு பொருந்தினால் மட்டும் பிணைய விவரங்களைச் சேர்க்கவும்.",
  "apply.select": "ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்",
  "loan.personal": "தனிநபர் கடன்",
  "loan.home": "வீட்டு கடன்",
  "loan.bike": "பைக் கடன்",
  "loan.car": "கார் கடன்",
  "loan.emergency": "அவசர கடன்",
  "loan.business": "வணிக கடன்",
  "frequency.daily": "தினசரி",
  "frequency.weekly": "வாராந்திர",
  "frequency.monthly": "மாதாந்திர",
  "collateral.none": "பிணையம் இல்லை",
  "collateral.gold": "தங்கம்",
  "collateral.silver": "வெள்ளி",
  "collateral.bike": "பைக் ஆவணங்கள்",
  "collateral.car": "கார் ஆவணங்கள்",
  "collateral.property": "வீடு/சொத்து ஆவணங்கள்",
  "collateral.phone": "மொபைல் போன்",
  "collateral.laptop": "லேப்டாப்",
  "collateral.other": "மற்ற அங்கீகரிக்கப்பட்ட பிணையம்",
  "dashboard.overview": "மேலோட்டம்",
  "dashboard.loans": "கடன்கள்",
  "dashboard.payments": "கட்டணங்கள்",
  "dashboard.documents": "ஆவணங்கள்",
  "dashboard.profile": "சுயவிவரம்",
  "dashboard.requests": "கடன் கோரிக்கைகள்",
  "dashboard.customers": "வாடிக்கையாளர்கள்",
  "dashboard.collateral": "பிணையம்",
  "dashboard.signOut": "வெளியேறு",
  "dashboard.menu": "மெனு",
  "dashboard.admin": "செயல்பாட்டு பணியிடம்",
  "dashboard.customer": "வாடிக்கையாளர் பணியிடம்",
  "admin.heading": "நிர்வாகிக்கு காலை வணக்கம்.",
  "admin.body": "விண்ணப்பங்கள், வசூல்கள் மற்றும் கவனம் தேவைப்படும் பணிகளைத் தெளிவாகப் பாருங்கள்.",
  "admin.totalApplications": "மொத்த விண்ணப்பங்கள்",
  "admin.activeLoans": "செயலில் உள்ள கடன்கள்",
  "admin.outstanding": "நிலுவைத் தொகை",
  "admin.collection": "இந்த மாத வசூல்",
  "admin.loanMix": "கடன் கலவை",
  "admin.collectionTrend": "வசூல் போக்கு",
  "admin.reviewQueue": "மதிப்பாய்வு வரிசை",
  "admin.reviewQueueBody": "முடிவு அல்லது ஆவணத் தொடர்ச்சி தேவைப்படும் விண்ணப்பங்கள்.",
  "admin.viewRequests": "கோரிக்கைகளைப் பாருங்கள்",
  "admin.approve": "ஒப்புதல்",
  "admin.reject": "நிராகரி",
  "admin.customersBody": "வாடிக்கையாளர் கணக்குகள் மற்றும் சுயவிவர தகவல்கள்.",
  "admin.loansBody": "செயலில் உள்ள கணக்குகள், திருப்பிச் செலுத்தல் நிலை மற்றும் அடுத்த செலுத்த வேண்டிய தேதிகள்.",
  "admin.paymentsBody": "பணம், UPI மற்றும் வங்கி பரிமாற்றங்களிலிருந்து சமீபத்திய ரசீதுகள்.",
  "admin.collateralBody": "சரிபார்ப்பு அல்லது மதிப்பாய்வுக்காக காத்திருக்கும் பிணைய பதிவுகள்.",
  "admin.documentsBody": "பதிவேற்றப்பட்ட கோப்புகள் மற்றும் ஆவண சரிபார்ப்பு நிலை.",
  "customer.heading": "மீண்டும் வரவேற்கிறோம்.",
  "customer.body": "உங்கள் தற்போதைய கடன் நிலை மற்றும் கவனிக்க வேண்டிய அடுத்த விஷயம் இங்கே.",
  "customer.outstanding": "நிலுவைத் தொகை",
  "customer.nextDue": "அடுத்த கட்டணம்",
  "customer.totalPaid": "மொத்தம் செலுத்தியது",
  "customer.loanStatus": "கடன் நிலை",
  "customer.schedule": "வரவிருக்கும் அட்டவணை",
  "customer.history": "கட்டண வரலாறு",
  "customer.viewLoan": "கடன் விவரங்களைப் பார்க்க",
  "customer.upload": "ஆவணத்தைப் பதிவேற்ற",
  "customer.updateProfile": "சுயவிவரத்தைப் புதுப்பிக்க",
  "customer.profileBody": "எங்கள் குழு உங்களைத் தொடர்புகொள்ள உங்கள் தொடர்பு மற்றும் வருமான விவரங்களைப் புதுப்பித்து வைக்கவும்.",
  "customer.documentsBody": "உங்கள் கடனுடன் தொடர்புடைய கோப்புகளை சேமித்து மதிப்பாய்வு செய்யவும்.",
  "customer.emi": "தவணை",
  "customer.due": "செலுத்த வேண்டியது",
  "customer.paid": "செலுத்தியது",
  "lab.eyebrow": "கிளையன்ட்-சைடு / முழு-ஸ்டாக் கற்றல்",
  "lab.heading": "உலாவி கருத்துகள் செயல்பாட்டில்.",
  "lab.body": "இந்தத் திட்டத்தில் பயன்படுத்தப்படும் CSS Box Model மற்றும் JavaScript Hoisting கருத்துகளுக்கான சிறிய செய்முறை ஆய்வகம்.",
  "lab.boxTitle": "CSS Box Model",
  "lab.boxBody": "கட்டுப்பாடுகளை மாற்றி, content, padding, border மற்றும் margin மொத்த அளவை எப்படி மாற்றுகின்றன என்பதைப் பாருங்கள்.",
  "lab.hoistingTitle": "JavaScript Hoisting",
  "lab.hoistingBody": "ஒவ்வொரு எடுத்துக்காட்டையும் இயக்கி, declaration-கள் செயல்பாட்டிற்கு முன் எவ்வாறு நடக்கின்றன என்பதைப் பாருங்கள்.",
  "lab.padding": "Padding",
  "lab.border": "Border",
  "lab.margin": "Margin",
  "lab.content": "Content",
  "lab.totalWidth": "மொத்த அகலம்",
  "lab.totalHeight": "மொத்த உயரம்",
  "lab.run": "எடுத்துக்காட்டை இயக்க",
  "lab.reset": "மீட்டமை",
  "lab.backendEyebrow": "சர்வர் / பின்புற கற்றல்",
  "lab.backendHeading": "API-க்குப் பின்னால் உள்ள கருத்துகளை உருவாக்குங்கள்.",
  "lab.backendBody": "Node.js கோரிக்கைப் பாதையைப் பாருங்கள், stream-ல் bytes நகர்வைக் கவனியுங்கள், MongoDB CRUD-ஐ பாதுகாப்பான உள்ளூர் playground-ல் பயிற்சி செய்யுங்கள்.",
  "lab.httpTitle": "Node.js HTTP server மற்றும் API",
  "lab.httpBody": "ஒரு route-ஐத் தேர்ந்தெடுத்து, HTTP server கோரிக்கையைப் பெற்று கட்டமைக்கப்பட்ட API பதிலை அனுப்புவதைப் பாருங்கள்.",
  "lab.httpRun": "கோரிக்கையை அனுப்பு",
  "lab.httpRequest": "கோரிக்கை",
  "lab.httpResponse": "பதில்",
  "lab.bufferTitle": "Buffers, streams மற்றும் events",
  "lab.bufferBody": "உரையை bytes-ஆக மாற்றி, chunks-ஆகப் பிரித்து, stream pipeline நகரும் போது events-ஐ வெளியிடுங்கள்.",
  "lab.bufferInput": "உள்ளீட்டு உரை",
  "lab.bufferRun": "Pipeline இயக்கவும்",
  "lab.bufferChunks": "Chunks",
  "lab.eventLog": "Event log",
  "lab.mongoTitle": "MongoDB CRUD playground",
  "lab.mongoBody": "MongoDB வடிவ function-களைப் பயன்படுத்தி memory collection-ல் create, read, update, delete செயல்பாடுகளைப் பயிற்சி செய்யுங்கள்.",
  "lab.mongoCreate": "Document உருவாக்கு",
  "lab.mongoRead": "Collection படி",
  "lab.mongoUpdate": "முதல் பதிவை மாற்று",
  "lab.mongoDelete": "முதல் பதிவை நீக்கு",
  "lab.mongoEmpty": "இன்னும் documents இல்லை",
  "lab.mongoNote": "இந்த browser-only simulator உண்மையான data-ஐ சேமிக்காமல் MongoDB CRUD முறையைப் பின்பற்றுகிறது.",
};

const dictionaries: Record<Language, TranslationMap> = { en: english, ta: tamil };

const getByPath = (dictionary: TranslationMap, key: string) => dictionary[key] ?? english[key] ?? key;

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    return window.localStorage.getItem("collatx-language") === "ta" ? "ta" : "en";
  });

  useEffect(() => {
    window.localStorage.setItem("collatx-language", language);
    document.documentElement.lang = language === "ta" ? "ta" : "en";
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    toggleLanguage: () => setLanguage((current) => (current === "en" ? "ta" : "en")),
    t: (key) => getByPath(dictionaries[language], key),
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}
